### ISSUE TITLE
Enable bitcode for tenjin cocoa pod

### ISSUE THREAD

**Issue by nosrak113** [Ordinance/tenjin-ios-sdk#6]
Pods/TenjinSDK/libTenjinSDKUniversal.a(TenjinSDK.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by farmcp** [comment]
@nosrak113 sorry for this - I'm a bit unfamiliar with this error. Do I need to rewrite the build scripts?

**Comment by farmcp** [comment]
https://github.com/Ordinance/tenjin-ios-sdk/pulls

**Comment by farmcp** [comment]
@nosrak113 can we close this issue now?

**Comment by nosrak113** [comment]
yep
